---
abstract: 'Microsoft Exchange Web Services Client'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200011, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EWS-Client
requires:
  Authen::NTLM: 0
  LWP::Authen::Ntlm: 0
  LWP::Protocol::https: 6.02
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=EWS-Client
  homepage: https://github.com/ollyg/EWS-Client/wiki
  repository: git://github.com/ollyg/EWS-Client.git
version: 1.111981
